// actionTypes.js
export const UPDATE_FORM_FIELD = 'UPDATE_FORM_FIELD';
export const RESET_FORM = 'RESET_FORM';
export const SUBMIT_FORM_REQUEST = 'SUBMIT_FORM_REQUEST';
export const SUBMIT_FORM_SUCCESS = 'SUBMIT_FORM_SUCCESS';
export const SUBMIT_FORM_FAILURE = 'SUBMIT_FORM_FAILURE';
